logging:
  config: classpath:log/logback-spring.xml
  path: d:/log
spring:
  application:
    name: jframework-web
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    template-resolver-order: 1
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/novels?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource




server:
  port: 8080

#security:
#  basic:
#    enabled: false
#  user:
#    name: admin
#    password: 123456

